= Musee Ullah

arbeiter@lae.is +
https://lae.is +
https://www.github.com/lae[Github] +
United States (Central)

== Objective

A senior systems administration and/or Rust/Python programming role with a focus
on systems/deployment automation and/or tools development.

== Employment

=== https://cover-corp.com/[COVER Corporation] - Tokyo, JP (Remote)

An entertainment company specializing in experiences via virtual and augmented
reality technologies.

==== Japanese-English Translator (Contract) - April 2020, ongoing

Provided localization, subtitling and translation checking services for
multimedia content and company press releases.

=== https://fressets.com/[Fressets&#44; Inc.] - Tokyo, JP (Remote)

A fintech company with a focus on blockchain infrastructure and security.

==== Senior Infrastructure Engineer (Contract) - July 2019 to January 2020

* introduced a continuous deployment workflow using Terraform and Terraform
  Cloud, making deployment environments self-documenting and reproducible.
* devised workflows for creating Salt formulae and Terraform modules to help
  simplify deployment tasks during in-house application development.
* developed an Ansible role for deploying and maintaining coin daemons.

=== https://fireeye.com[FireEye, Inc.] - Milpitas, CA

A cybersecurity company with a renown background in malware detection.

==== Senior Research Infrastructure Engineer - January 2018 to July 2018
==== Research Infrastructure Engineer (Lead) - March 2015 to December 2017

* led a team of 3 DevOps engineers, mentoring them on topics like writing well
  defined Ansible roles and managing distributed database/VM/storage clusters
* provided infrastructure services to researchers and R&D teams, e.g. planning
  and deployment of malware analysis services
* wrote a small tool in Rust to simplify controlling servers via IPMI
* implemented system lifecycle automation processes with a template-based PXE
  server for provisioning bare metal systems, including FireEye's appliance OS
  (saving researchers hundreds of hours of manual setup), and Ansible for
  configuration management and software deployment
* deployed and managed a continuous integration environment around Drone CI
* re-architected an internal Django application around minimal Docker images
* deployed (several involved writing open-sourced Ansible roles) and managed
  distributed systems such as Ceph, Cassandra, Elasticsearch and internal
  FireEye systems, as well as highly available Proxmox virtualization clusters
  (on top of which we maintain services like GitHub Enterprise and NetBox)
* managed inventory and hardware for a fleet of ~1000 servers
* architected and deployed monitoring environment around Prometheus

=== http://sleepygiant.com[Sleepy Giant Entertainment] - Chicago, IL

A game infrastructure development company.

==== Systems Engineer - July 2013 to September 2014

* orchestrated servers with Chef and other automation utilities
* worked with several Amazon Web Services, including RDS, VPC, Beanstalk
* replaced part of SG's development cycle with Docker (Jenkins CI)
* wrote various scripts in Python, Ruby and Bash
* was responsible for the security audit after the Heartbleed PSA

=== http://hostgator.com[HostGator.Com, LLC] - Austin, TX

A shared web hosting company who also offers dedicated servers/VMs.

==== Systems Monitoring - December 2011 to July 2012

* monitored >4500 machines remotely (SoftLayer) using Zabbix/ZMonitor
* dealt with user abuse, compromised clients, broken configurations, and other resource usage issues
* handled network abuse/issues by either firewall or escalating to SL (UDP/SYN floods, Slowloris)
* sole assistant from the monitoring team during HG's architecture migration (32->64bit)
* wrote http://forums.hostgator.com/search.php?do=finduser&u=126179[public announcements]
  on the http://forums.hostgator.com/network-status-f14.html[network status forums]
  for extended downtime issues.  

==== Systems Administrator - June 2011 to July 2012

* was primarily help desk support, handling website/database/application errors and
  issues, backups/restorations, triage, software upgrades and installations.
* Filed internal bug reports and wrote documentation for company wikis and knowledgebase.

=== Contracted Roles

* http://batee.com[*batee.com*] - redesigned website using Bootstrap; moved
  editing process from disparate HTML files to Jekyll static site generation

== Volunteering

* *Simple Mona* (2014-2015) - sole administrator of this pool for the Monacoin
  cryptocurrency - https://github.com/lae/simplemona[development halted] +
  ** involved administrating a RabbitMQ cluster, developing in Python (Flask),
    and querying in Postgres +
  ** i18n support, added Japanese translation (by me and a couple native speakers) +
* http://knightsofreason.net[*Knights of Reason*] - primary contact for
  technical issues, server owner/co-admin, forum moderator.
  ([server documentation](https://wiki.milkteafuzz.com)) +
* http://thebikeproject.org[*The Bike Project of Urbana-Champaign*]
  (Urbana, IL, 8/2010-2/2011) - bike mechanic and technologist, e.g. repurposed
  old laptops with Debian for use at the shop. +

== Projects / One-Offs

* https://github.com/lae/ansible-role-proxmox[*Proxmox Ansible Role*] - A role for deploying and configuring complete Proxmox virtualization clusters.  
* https://github.com/lae/ansible-role-netbox[*NetBox Ansible Role*] - A role for deploying and configuring the NetBox Django application.  
* https://github.com/lae/zmonitor[*ZMonitor*] - cli dashboard for Zabbix
  written in Ruby.  
* https://github.com/lae/wagnaria[*Wagnaria*] - fansubbing organisation
  tool written in bottle.py/Python and AngularJS
  (https://c.milkteafuzz.com/[copy of it in production]).  
* https://github.com/lae/sift[*SIF Tracker*] - per-user leaderboard tracking
  web application written in Flask/Python, with some backend bits in Ruby  

== Familiarities / Preferences

*distros*: arch linux, centos, debian, coreos, ubuntu (16+) +
*lang*: bash, python, rust, ruby, markdown, json +
*apps*: nginx, postgresql, mysql, etherpad, chef, aegisub +
*workflow*: ansible, git, vim, i3wm, remmina, lxc, vagrant/virtualbox/qemu-kvm, bash (x2)

== Education

*University of Illinois at Urbana-Champaign* - 2010 -- 2011 - East Asian
  Languages and Cultures +
*De Anza College* - 2016 -- 2019 - Systems Programming +
*Western Governor's University* - 2020 -- 2022 - BS Computer Science +
